### ISSUE TITLE
Problem getting specific module from Go repository (Go 1.13)

### ISSUE THREAD

**Issue by jackwhelpton** [jfrog/jfrog-cli#468] opened 2019-10-06 20:54 UTC
With GOPROXY set to point to Artifactory, I can produce an error as follows:

```
mkdir tmp
cd tmp
go mod init github.com/jackwhelpton/tmp
go get github.com/Nvveen/Gotty

go: finding github.com latest
go: finding github.com/Nvveen/Gotty latest
go: downloading github.com/Nvveen/Gotty v0.0.0-20161109172849-6018b68f96b8
verifying github.com/Nvveen/Gotty@v0.0.0-20161109172849-6018b68f96b8: github.com/Nvveen/Gotty@v0.0.0-20161109172849-6018b68f96b8: reading https://sum.golang.org/lookup/github.com/!nvveen/!gotty@v0.0.0-20161109172849-6018b68f96b8: 410 Gone
```

Disabling the proxy, fetching this module works as expected.

**Comment by jackwhelpton** [comment] 2019-10-06 20:57
As a related question, is it recommended to set `GOSUMDB=off` recommended when using Artifactory as a module cache?

**Comment by jackwhelpton** [comment] 2019-10-06 21:11
This is using a private Go registry, here's the same output with the public one (gocenter.io):

```
go get github.com/Nvveen/Gotty
go: finding github.com/Nvveen/Gotty latest
go: downloading github.com/Nvveen/Gotty v0.0.0-20161109172849-6018b68f96b8
verifying github.com/Nvveen/Gotty@v0.0.0-20161109172849-6018b68f96b8: github.com/Nvveen/Gotty@v0.0.0-20161109172849-6018b68f96b8: reading https://gocenter.io/sumdb/sum.golang.org/lookup/github.com/!nvveen/!gotty@v0.0.0-20161109172849-6018b68f96b8: 404 Not Found
```

**Comment by jackwhelpton** [comment] 2019-10-06 21:29
What's interesting is that it's pulling a commit that seems to be part of a PR rather than master:

https://github.com/Nvveen/Gotty/pull/1/commits/6018b68f96b839edfbe3fb48668853f5dbad88a3

I wonder if this is causing an issue somehow?

**Comment by jackwhelpton** [comment] 2019-10-06 21:31
It's something to do with this, as with the GOPROXY disabled what gets added to the mod file is:

```
require github.com/Nvveen/Gotty v0.0.0-20120604004816-cd527374f1e5 // indirect
```

**Comment by eyalbe4** [comment] 2019-10-06 23:23
@jackwhelpton,
Please use the latest JFrog CLI version (currently 1.29.1) which includes compatibility fixes for go 1.13.
Also, go 1.13 uses go's new checksum database by default, to verify every module it downloads. Private modules are unknown to the database and will therefore fail the verification (see the **410 Gone** message in the log you provided)
The solution is to exclude private modules from being verified, by adding them to the *GONOSUMDB* environment variable. It also allows adding the prefix of the module name, in your case for example:
**export GONOSUMDB=github.com/Nvveen**
will exclude the verification of all modules under *github.com/Nvveen*.
Please let us know if this resolves the issue.

**Comment by jackwhelpton** [comment] 2019-10-07 21:43
Yep, I have the GONOSUMDB set for our private repos, but as far as I can tell github.com/Nvveen is public. Let me check Jfrog version...

**Comment by jackwhelpton** [comment] 2019-10-07 22:01
I've also just run into a particularly nasty case where https://github.com/jfrog/jfrog-cli/issues/376 prevents me fetching dependencies with the proxy disabled and this one prevents me doing the same with it enabled.

**Comment by eyalbe4** [comment] 2019-10-07 22:42
@jackwhelpton,
Can you please help me figure this one out, by sharing a small project that replicates this error?

**Comment by jackwhelpton** [comment] 2019-10-07 22:44
Sure, just follow the steps above. I don't think you need a project, you can just create an empty directory, run `go mod init` and then `go get` the troublesome module. As long as I have an Artifactory GOPROXY set (either our internal company one or gocenter.io), I see some kind of error as detailed above.

**Comment by jackwhelpton** [comment] 2019-10-09 00:52
I'm seeing similar problems with `gopkg.in/square/go-jose.v2`, although in that case I think I see checksum missing errors without the module proxy enabled too.

**Comment by eyalbe4** [comment] 2019-10-10 15:42
@jackwhelpton,
The https://github.com/Nvveen/Gotty modules has no tags (no versions on GitHub).
That's why when I tried to get it through Artifactory (by having the GOPROXY configured) I received 404 Not Found:
```
eyalb-mac:go-issue eyalb$ echo $GOPROXY
https://XXX:YYY@ecosysjfrog.jfrog.io/ecosysjfrog/api/gp/go
eyalb-mac:go-issue eyalb$ 
eyalb-mac:go-issue eyalb$ 
eyalb-mac:go-issue eyalb$ go get github.com/Nvveen/Gotty
go get github.com/Nvveen/Gotty: module github.com/Nvveen/Gotty: reading https://eyalb:%5Bredacted%5D@ecosysjfrog.jfrog.io/ecosysjfrog/api/gp/go/github.com/%21nvveen/%21gotty/@v/list: 404 Not Found
``` 
Since you actually downloaded the module from Artifactory (before failing of the checksum validation), I assume that you already have this module published in Artifactory. Is this correct?
If so, there's a chance it was published to Artifactory using the *jfrog rt gp* command with a bad checksum, due to the issue  fixes.
What do you think? Can this be the cause of then issue?

**Comment by eyalbe4** [comment] 2019-10-23 10:26
@jackwhelpton,
Please let me know if you need further assistance or have any comments related to this issue.

**Comment by jackwhelpton** [comment] 2019-10-23 16:59
I haven't seen this recently and I've purged our artifactory cache a few times for similar reasons, so it's quite possible what you've suggested is the explanation. That said, am I correct in thinking that this page indicates the module _is_ cached in gocenter, even though the checksum is missing?

https://search.gocenter.io/github.com~2FNvveen~2FGotty/info?version=v0.0.0-20161109172849-6018b68f96b8

**Comment by eyalbe4** [comment] 2019-10-29 08:10
@jackwhelpton,
Yes, GoCenter has this package as the link shows.

**Comment by eyalbe4** [comment] 2019-11-28 11:41
@jackwhelpton,
I'm closing this issue for now, but please let me know if you need further assistance.

**Closed by eyalbe4** 2019-11-28 11:41 UTC
