### ISSUE TITLE
Artifacts uploaded with 202 status through CLI are throwing failure message in the CLI logs

### ISSUE THREAD

**Issue by sandeepanikapati** [jfrog/jfrog-cli#1265] opened 2021-10-25 15:01 UTC
Description:

While uploading the maven artifacts to the Artifactory using CLI, there is an error message saying “Failed uploading the artifact" even though the artifact is successfully deployed (Verified in the UI). 

1) Run the below CLI upload command on the below file structure

jfrog rt u "org/jfrog/example/maven-example/1.0-SNAPSHOT/*" maven-test

File Structure:
org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.jar
org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.pom
org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-metadata.xml
org/jfrog/example/maven-example/maven-metadata.xml

For the artifact ("maven-example/maven-metadata.xml") with “202” Artifactory response, CLI logs are giving a failed message saying “one artifact failed to upload”. However, this artifact was uploaded successfully, I have attached the screenshot.
![UI_upload](https://user-images.githubusercontent.com/66374485/138720200-b8e1b473-1140-46c7-a984-4469347a6e92.png)

Please find below logs

CLI Console Log:
{
"status": "failure",
"totals": {
"success": 2,
"failure": 1
}
}

CLI logs:
[Info] [Thread 1] Uploading artifact: org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.jar
[Info] [Thread 0] Uploading artifact: org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.pom
[Info] [Thread 2] Uploading artifact: org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-metadata.xml
[Error] [Thread 2] Artifactory response: 202 Accepted
 
[Error] Failed uploading 1 artifacts.
 
Artifactory logs:
Oct 21, 2021 @ 16:39:39.595 2021-10-21T16:39:39.595Z [d3bddb4ef005a95b] [ACCEPTED DEPLOY] maven-local:org/jfrog/example/maven-example/maven-metadata.xml for client : sandeep / .
Oct 21, 2021 @ 16:39:39.538 2021-10-21T16:39:39.538Z [4dca9fabd58f25a6] [ACCEPTED DEPLOY] maven-local:org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.pom for client : sandeep / 52.215.237.185.
Oct 21, 2021 @ 16:39:39.537 2021-10-21T16:39:39.537Z [4dca9fabd58f25a6] [ACCEPTED DEPLOY] maven-local:org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-metadata.xml for client : sandeep / 52.215.237.185.
Oct 21, 2021 @ 16:39:39.394 2021-10-21T16:39:39.394Z [f4e152dba05e9ec0] [ACCEPTED DEPLOY] maven-local:org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.jar for client : sandeep / 52.215.237.185.

Expected behavior:

As the upload was successful, CLI logs should display the "upload successful" message.

Actual behavior:
CLI is throwing an error message for the "202 Accepted" status artifacts

[Info] [Thread 2] Uploading artifact: org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-metadata.xml
[Info] [Thread 0] Uploading artifact: org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.pom
[Info] [Thread 1] Uploading artifact: org/jfrog/example/maven-example/1.0-SNAPSHOT/maven-example-1.0-20210406.120725-1.jar
[Error] [Thread 2] Artifactory response: 202 Accepted
[Error] Failed uploading 1 artifacts.

**Versions**
- JFrog CLI version:  2.4.1
- JFrog CLI operating system: Mac
- Artifactory Version: 7.27.6

**Comment by shobhitDream11** [comment] 2021-11-15 10:56
I am facing the same problem while uploading my artefacts

**Comment by sverdlov93** [comment] 2022-08-02 16:54
Hi @sandeepanikapati  and @shobhitDream11,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
We believe that the issue was fixed on JFrog CLI 2.23.0, so feel free to update the cli version to the latest.
Looking forward to your feedback on it.

**Closed by sverdlov93** 2022-08-02 16:55 UTC
Labels: bug
