### ISSUE TITLE
Contributing Guidelines CLA Link broken

### ISSUE THREAD

**Issue by Snapstromegon** [jfrog/jfrog-cli#654] opened 2020-03-27 07:40 UTC
**Describe the bug**
The contributing guidelines CLA link resolves to "This agreement is no longer accessible for signature. If you feel you have reached this page in error please contact the person who directed you to this page to sign the agreement.".

**To Reproduce**
Open the Contribution guide and click the CLA link.

**Expected behavior**
The CLA to show up for signing (or even reading).

**Screenshots**
![image](https://user-images.githubusercontent.com/18480654/77733147-a7781180-7006-11ea-96ef-465d94413468.png)

**Comment by yahavi** [comment] 2020-03-30 15:10
Thanks for reporting this issue, @Snapstromegon.
We are working on a fix.

**Comment by eyalbe4** [comment] 2020-03-31 12:27
@Snapstromegon - the issue is fixed now.
Sorry for the inconvenience caused by this.
Feel free to close this issue.

**Closed** 2020-03-31 12:33 UTC
Labels: bug
