### ISSUE TITLE
jfrog rt build-publish regression

### ISSUE THREAD

**Issue by remy-tiitre** [jfrog/jfrog-cli#1276] opened 2021-11-09 14:21 UTC
**Describe the bug**
I upgraded jfrog-cli from 2.3.0 to 2.4.1 and I can confirm that the problem is still there with 2.5.1. After the upgrade jfrog rt build-publish errors out with "unexpected end of JSON input" error.

**To Reproduce**
Not sure that it reproduces the problem but thats my flow. Values have been replaced as I don't want to publish internal information and I doubt it has anything to do with the issue. We have the same problem with a lot of projects that tried to use the updated version:
export JFROG_CLI_DEPENDENCIES_DIR="/some-project-folder/.jfrog"
export JFROG_CLI_EXTRACTORS_REMOTE="jfrog-cli-extractors/jfrog-oss"
export JFROG_CLI_BUILD_NAME="project-name"
export JFROG_CLI_BUILD_NUMBER="0"
export JFROG_CLI_BUILD_URL="local"
jfrog config add build-server --interactive=false --artifactory-url="https://localhost/artifactory/" --access-token=[SECRET_TOKEN]
jfrog config use build-server
jfrog rt gradle-config --use-wrapper=true --uses-plugin=true
jfrog rt gradle 'build -Dspring.profiles.active=test'
jfrog rt gradle-config --use-wrapper=true --uses-plugin=true --server-id-deploy=build-server --repo-deploy=application-gradle-dev-local
jfrog rt gradle artifactoryPublish
jfrog rt build-add-git
jfrog rt build-publish

All other jfrog rt commands are fine, its the build-publish that fails. It seems when I change the version from 5 to 4 in jfrog.conf then it will not fail. But the thing is this config file is generated by these commands. It is not persisted, every time build starts it is in clean container.

**Versions**
- JFrog CLI version: 2.4.1
- JFrog CLI operating system: CentOS 7
- Artifactory Version: 7.27.6

**Additional context**
When I revert back to older build image that uses jfrog-cli 2.3.0 the problem goes away.

**Comment by remy-tiitre** [comment] 2021-11-10 08:59
Changeing version from 5 to 4 was misleading. It will not work, it just starts the interactive configuration if I run those commands manually. So it definately seems to be an issue with the config files.

**Comment by remy-tiitre** [comment] 2021-11-10 09:49
I add also my ~/.jfrog/jfrog-cli.conf.v5 content replacing some values:
```
{
  "servers": [
    {
      "artifactoryUrl": "https://localhost/artifactory/",
      "serverId": "jfrog-cli-extractors"
    },
    {
      "artifactoryUrl": "https://localhost/artifactory/",
      "accessToken": "[SECRET_TOKEN]",
      "serverId": "build-server",
      "isDefault": true
    }
  ],
  "version": "5"
}
```

**Comment by eyalbe4** [comment] 2021-11-11 21:41
@remy-tiitre,
There's a chance that one of jfrog-cli's releases included a bug, which caused jfrog-cli's config to not get upgraded probably. I apologize for the inconvenience caused by this. 
Will you be able to try and remove jfrog-cli's configuration file (after backing it up) and then recreate the configuration using the ```jfrog c add``` command?

**Comment by remy-tiitre** [comment] 2021-11-12 08:15
As I mentionied in the first post our build environments are clean containers. They don't have any jfrog cli conf files in them. Configuration is generated from scratch every time with the commands I provided.

**Comment by eyalbe4** [comment] 2021-11-13 10:04
@remy-tiitre - 
Are you sure this machine doesn't have more than one JFrog CLI version being executed? JFrog CLI automatically upgrades a version 4 config to version 5. However, an older version of JFrog CLI, which is not aware of version 5, and require version 4, may fail.
To be honest, I can think of another scenario that can cause this. If you're able to provide with a series of reproducible steps that can lead to this, which we can run in clean slate container, that would be greatly useful.

**Comment by remy-tiitre** [comment] 2021-11-16 16:55
I will try to replicate it in a community accessible images. We have our own custom ones for internal use that I can't share. But whats most mystifying for me is that its regression with version and that it only happens when you try to publish the build. I sent detailed logs to JFrog support ticket as we are paying customers and we had issue open there as well.

**Comment by yahavi** [comment] 2021-11-24 14:54
@remy-tiitre 
Thanks for reporting this issue. We managed to reproduce and hopefully fix this issue in https://github.com/jfrog/build-info-go/pull/16.
The fix may be included in the next release.
We'll keep you updated.

**Comment by yahavi** [comment] 2021-11-25 13:15
@remy-tiitre
JFrog CLI 2.6.2 is released. This version includes the fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.

**Closed by yahavi** 2021-11-25 13:15 UTC
Labels: bug
