### ISSUE TITLE
Local deps replace statements are breaking publishing deps to Artifactory

### ISSUE THREAD

**Issue by bguendy** [jfrog/jfrog-cli#480] opened 2019-10-28 18:51 UTC
Using golang 1.13.3 and jfrog cli 1.29.2 and same behaviour with jfrog cli 1.30.0. Having local replace statements breaks the deps publishing to artifactory.

Here are the steps to reproduce the issue:

$ git clone https://github.com/eliasnaur/gomodtidy.git
Cloning into 'gomodtidy'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 2), reused 17 (delta 2), pack-reused 0
Unpacking objects: 100% (17/17), done.
$ cd gomodtidy/main/

$ go mod edit -replace github.com/eliasnaur/gomodtidy/lib=../lib

$ cat go.mod
module github.com/eliasnaur/gomodtidy/main
go 1.13
require github.com/eliasnaur/gomodtidy/lib v0.0.0
replace github.com/eliasnaur/gomodtidy/lib => ../lib
 
$ env | grep GO
GO111MODULE=on
GOSUMDB=off
GOROOT=/opt/go1.13.3

$ jfrog --version
jfrog version 1.29.2

$ jfrog rt go --publish-deps 'build ./...' go-modules

At this point the project is built and no deps are published to artifactory go proxy.

While reverting the change in go.mod to remove the local replace statement:

$ cat go.mod
module github.com/eliasnaur/gomodtidy/main

go 1.13

require github.com/eliasnaur/gomodtidy/lib v0.0.0-20190401155538-6de8c4f5b51e

$ jfrog rt go --publish-deps 'build ./...' go-modules
This command builds the project and publishes the deps successfully.

**Comment by hugares** [comment] 2019-10-29 18:33
FYI: I am working on the issue and I have a fix for it. The problems is caused by the way gocmd handle the replace statements which points to on-disk location.

While implementing the fix, I realised that there are other things that need to be fixed with the handling of replace statements. I will push a few PR in that area of the code to address all issues.

**Comment by eyalbe4** [comment] 2020-03-30 21:42
@bguendy,
I believe this issue can be closed, following the work done by @hugares.
Please let me know if it shouldn't.
Thanks

**Closed by eyalbe4** 2020-03-30 21:42 UTC

**Comment by bguendy** [comment] 2020-03-30 22:07
Yes, this should be closed
