### ISSUE TITLE
Unexpected behavior when running dotnet restore with build-name and build-number

### ISSUE THREAD

**Issue by bmarroquin** [jfrog/jfrog-cli#1438] opened 2022-02-14 19:09 UTC
**Describe the bug**
When I run `jf dotnet restore --build-name jfrog-test --build-number 3 --project nmod`, the process hangs and consumes a lot of memory. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3230744/153929562-8cae7214-2c7f-4735-a899-793d762f34e3.png)

**Versions**
- JFrog CLI version: 2.12.1
- JFrog CLI operating system: Windows 10
- Artifactory Version:  7.27.10

**Additional context**
When I run without build number and build-name there are no problems.

**Comment by eyalbe4** [comment] 2022-02-14 20:36
@bmarroquin,
Thanks for reporting this issue. 
We'd like to see the logs to understand the cause of this issue. Will you be able to set the  JFROG_CLI_LOG_LEVEL environment variable to DEBUG, run the command and share with us the logs here?

**Comment by bmarroquin** [comment] 2022-02-14 22:00
It eventually hit an out of memory issue. Log for that
```
runtime: VirtualAlloc of 4707000320 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0xb2b1ca, 0xccb877c000})
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/panic.go:1198 +0x76
runtime.sysUsed(0xccb4d00000, 0x1188f2000)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0x13b2560, 0x8c479, 0x0, 0x0)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/mheap.go:1268 +0x3a5
runtime.(*mheap).alloc.func1()
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/mheap.go:913 +0x69
runtime.systemstack()
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/asm_amd64.s:383 +0x4e

goroutine 1 [running]:
runtime.systemstack_switch()
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/asm_amd64.s:350 fp=0xc000106628 sp=0xc000106620 pc=0x112360
runtime.(*mheap).alloc(0x1188f2000, 0x8c479, 0x88, 0x1)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/mheap.go:907 +0x73 fp=0xc000106678 sp=0xc000106628 pc=0xd6433
runtime.(*mcache).allocLarge(0xc000058000, 0x1188f2000, 0x90, 0x0)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/mcache.go:227 +0x89 fp=0xc0001066d8 sp=0xc000106678 pc=0xc6ca9
runtime.mallocgc(0x1188f2000, 0x9cc300, 0x1)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/malloc.go:1082 +0x5c5 fp=0xc000106758 sp=0xc0001066d8 pc=0xbd0c5
runtime.growslice(0x9cc300, {0xca20d00000, 0xc0003b5020, 0xc00978b400}, 0x0)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/slice.go:267 +0x4ea fp=0xc0001067c0 sp=0xc000106758 pc=0xfa46a
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc00002e138, 0x14}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xcb37b80000, 0x1d4aa0, 0x227eaa}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:107 +0x2c5 fp=0xc000106950 sp=0xc0001067c0 pc=0x8e3a05
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc000239068, 0x18}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0005f8900, 0x1c, 0x20}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc000106ae0 sp=0xc000106950 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc0000860c0, 0x24}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000128048, 0x1, 0x1}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc000106c70 sp=0xc000106ae0 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc0003ce570, 0x2b}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000128030, 0x1, 0x1}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc000106e00 sp=0xc000106c70 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc000277800, 0x2d}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0002c20a8, 0x1, 0x1}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc000106f90 sp=0xc000106e00 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc0003a60c0, 0x15}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0002c21e0, 0x1, 0x1}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc000107120 sp=0xc000106f90 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc00000e3c0, 0x1a}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0002c21c8, 0x1, 0x1}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc0001072b0 sp=0xc000107120 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.populateRequestedBy({{0xc000278ec0, 0xd}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0002c3c98, 0x1, 0x1}, ...}, ...)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:113 +0x16b fp=0xc000107440 sp=0xc0001072b0 pc=0x8e38ab
github.com/jfrog/jfrog-cli-core/v2/artifactory/utils/dotnet/solution.(*solution).BuildInfo(0xc000392050, {0x0, 0x0})
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/utils/dotnet/solution/solution.go:76 +0x628 fp=0xc000107788 sp=0xc000107440 pc=0x8e36e8
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/dotnet.(*DotnetCommand).Exec(0xc00022efc0)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/commands/dotnet/dotnetcommand.go:133 +0x343 fp=0xc000107868 sp=0xc000107788 pc=0x8e5843
github.com/jfrog/jfrog-cli-core/v2/artifactory/commands/dotnet.(*DotnetCoreCliCommand).Run(0xc0000068a0)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/artifactory/commands/dotnet/dotnetcorecli.go:27 +0x46 fp=0xc000107880 sp=0xc000107868 pc=0x8e7766
github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec({0xcaade8, 0xc0000068a0})
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/common/commands/command.go:26 +0xad fp=0xc0001078b8 sp=0xc000107880 pc=0x7d078d
github.com/jfrog/jfrog-cli/buildtools.DotnetCmd(0xc000154dc0)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:551 +0x2ab fp=0xc000107958 sp=0xc0001078b8 pc=0x92c32b
github.com/jfrog/jfrog-cli/buildtools.GetCommands.func10(0xc000154dc0)
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/buildtools/cli.go:187 +0x19 fp=0xc000107970 sp=0xc000107958 pc=0x92ee59
github.com/urfave/cli.HandleAction({0x9e7da0, 0xb7a078}, 0x6)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8 fp=0xc000107988 sp=0xc000107970 pc=0x7efec8
github.com/urfave/cli.Command.Run({{0xb230c0, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0xb5c196, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652 fp=0xc000107b68 sp=0xc000107988 pc=0x7f0f52
github.com/urfave/cli.(*App).Run(0xc00014aa80, {0xc00012c000, 0x5, 0x8})
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705 fp=0xc000107ea8 sp=0xc000107b68 pc=0x7ee085
main.execMain()
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:104 +0x307 fp=0xc000107f30 sp=0xc000107ea8 pc=0x9583c7
main.main()
        /var/jenkins_home/workspace/eco-system/release/jfrog-cli-release/temp/jfrog-cli/main.go:68 +0x25 fp=0xc000107f80 sp=0xc000107f30 pc=0x957fe5
runtime.main()
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/proc.go:255 +0x217 fp=0xc000107fe0 sp=0xc000107f80 pc=0xe9077
runtime.goexit()
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go-1.17.2/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000107fe8 sp=0xc000107fe0 pc=0x1146e1

goroutine 6 [chan send, 114 minutes]:
github.com/jfrog/jfrog-cli-core/v2/common/commands.signalReportUsageFinished(0x0)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/common/commands/command.go:65 +0x25
github.com/jfrog/jfrog-cli-core/v2/common/commands.reportUsage({0xcaade8, 0xc0000068a0}, 0x0)
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/common/commands/command.go:61 +0x4bb
created by github.com/jfrog/jfrog-cli-core/v2/common/commands.Exec
        /root/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.9.1/common/commands/command.go:24 +0x9d
```

**Comment by bmarroquin** [comment] 2022-02-14 22:02
Here is the debug log.
```
PS JfrogTesting> jf dotnet restore --build-name=jfrog-test --build-number=3 --project=nmod
13:59:26 [Debug] Found resolver in the config file C:\Users\marroqb\source\repos\JfrogTesting\.jfrog\projects\dotnet.yaml
13:59:26 [Debug] Usage Report: Sending info...
13:59:26 [Debug] Sending HTTP GET request to: .../artifactory/api/system/version
13:59:27 [Debug] using .NET SDK Core 5.0.104

13:59:27 [Info] Running dotnet...
13:59:27 [Debug] Nuget config file created at: C:\Users\marroqb\AppData\Local\Temp\jfrog.cli.temp.-1644875967-853117565\jfrog.cli.nuget.1920100731
13:59:27 [Debug] The Artifactory version is: 7.27.10
13:59:27 [Debug] Sending HTTP POST request to: .../artifactory/api/system/usage
13:59:27 [Debug] Usage Report: Artifactory response: 200
13:59:27 [Debug] Usage Report: Usage info sent successfully.
  Determining projects to restore...
  Restored C:\Users\marroqb\source\repos\JfrogTesting\JfrogTesting\JfrogTesting.csproj (in 400 ms).
13:59:29 [Debug] Found C:\Users\marroqb\source\repos\JfrogTesting\JfrogTesting\obj\project.assets.json file for project: JfrogTesting
13:59:29 [Debug] Saving build general details at: C:\Users\marroqb\AppData\Local\Temp\jfrog\builds\8edac6ee9e88abf29175396e495d16279394c50685ee0ff8bb9488bb1a507f02\partials
```

**Comment by talarian1** [comment] 2022-02-15 13:10
Hi @bmarroquin,
Thanks for the log sharing. Unfortunately, I was not able to reproduce this issue on my env.
Could you please share with us the test project you used as well?

**Comment by bmarroquin** [comment] 2022-02-16 02:38
@talarian1 Sorry I didn't get to send it in today. The project is an empty .net 5.0  with one dependency (log4net)

**Comment by eyalbe4** [comment] 2022-02-16 02:55
@bmarroquin -
Probably some edge case we need to handle. I believe that once you share the project that causes this, @talarian1 will be able to pinpoint and fix the issue.

**Comment by bmarroquin** [comment] 2022-02-16 17:45
[ArtifactoryTesting.zip](https://github.com/jfrog/jfrog-cli/files/8082169/ArtifactoryTesting.zip)
Here are the the files
Some more data:
I tried on two different windows machines and see the same behavior
I tried changing the temp folder to a new location and same behavior
I tried recreating the project and same behavior
Xray is enabled on the antifactory server

**Comment by talarian1** [comment] 2022-02-24 14:19
@bmarroquin, JFrog CLI v2.13.0 is released and includes a fix to this issue. 
We will appreciate any feedback.

**Comment by Smasherr** [comment] 2022-03-02 16:38
> @bmarroquin, JFrog CLI v2.13.0 is released and includes a fix to this issue. We will appreciate any feedback.

We also had out-of-memory errors in our pipeline with v2.12.1. I've set `JFROG_CLI_PIPELINE_REQUESTED_VERSION_AZURE` to 2.13.0 and the pipeline works now.

Would be nice to see [4a0e81d](https://github.com/Smasherr/jfrog-azure-devops-extension/commit/4a0e81dc9f4ad713e89b1dcdb343ee1cdbe7f8f4) merged soon to have it as the default version.

**Comment by cschyma** [comment] 2022-03-03 07:28
> @bmarroquin, JFrog CLI v2.13.0 is released and includes a fix to this issue. We will appreciate any feedback.

Fixed the timeout issue for us. Thanks for your fast response!

**Comment by bmarroquin** [comment] 2022-03-05 16:16
> @bmarroquin, JFrog CLI v2.13.0 is released and includes a fix to this issue. We will appreciate any feedback.

I will test it out and confirm on Monday. Sorry for the delay in response.

**Closed** 2022-03-16 16:04 UTC
Labels: bug
