### ISSUE TITLE
rt build-clean always fails in 1.29.0

### ISSUE THREAD

**Issue by AndreGleichner** [jfrog/jfrog-cli#462] opened 2019-09-26 11:02 UTC
Due to this commit: https://github.com/jfrog/jfrog-cli/commit/0e5388520d79e02de54701932adabdfe830237b7 any calls to jfrog rt bc... fails with "[Error] Wrong number of arguments..."
Argument count check in cli.go line 2202 is wrong. Instead of 
if c.NArg() > 1 {
it shall be 
if c.NArg() > 2 {

**Comment by yahavi** [comment] 2019-09-26 11:23
Thanks for reporting this issue, @AndreGleichner!
This [PR](https://github.com/jfrog/jfrog-cli/pull/463) should resolve this.
You can downgrade to 1.28.0, or, if you need a snapshot version, please let us know.

**Comment by AndreGleichner** [comment] 2019-09-26 12:27
Thanx for your fast response :)

Up until now some of my scripts can only update to the lastest available jfrog.exe version and distribute this to quite a bunch of machines where its used while building our SW. That script not only updates jfrog but updates a lot of our build machinery. So currently I'm in a situation where I can't update parts of our build stuff.
Most probably I'll now implement some kind of workaround to be able to stick with an older jfrog...

So no need for an urgent update.

**Comment by eyalbe4** [comment] 2019-09-26 12:29
Thank you @AndreGleichner for reporting this issue and pinpointing the cause and thanks @yahavi for fixing this so quickly!
Version **1.29.1** is released with this fix.

**Comment by eyalbe4** [comment] 2019-09-26 12:37
Sure @AndreGleichner - 
We'll need to investigate how this bug slipped through defences.
The *TestArtifactoryCleanBuildInfo* function should have cought that.

**Comment by eyalbe4** [comment] 2019-10-29 08:35
Closing this one @AndreGleichner.
Let me know if further assistance is needed.

**Closed by eyalbe4** 2019-10-29 08:35 UTC
