### ISSUE TITLE
Cannot install python libs when there is no setup.py in the project

### ISSUE THREAD

**Issue by tarek-ri** [jfrog/jfrog-cli#948] opened 2021-01-04 23:28 UTC
I have a project that utilises poetry and naturally it does not have a setup.py as it is not required. When I try to install packages using the GitHub Actions cli I get the following error:

`Error:  Could not find setup.py file in current directory: /home/runner/work/my-project/my-project`

I wrote the following GitHub Actions workflow for a dummy project which has no setup.py:

`name: "Build Python using JFrog CLI Example"
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.8'
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          version: '1.43.1'
        env:
          JF_SERVER_NAME: ${{ secrets.JFROG_SERVER_NAME }}
      - name: Run JFrog CLI
        run: |
          # Ping the server
          jfrog rt ping
          # Configure project resolution repository
          jfrog rt pipc --server-id-resolve ${{ secrets.JFROG_SERVER_NAME }} --repo-resolve pypi-local
          # Install project dependancies
          JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt pipi --upgrade pip setuptools wheel poetry
          # JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt pipi flask`
Observations:
1. I get the error msg mentioned above
2. Adding the flask package inline with the rest installs it before showing the error 

Am I missing something or is this an actual issue?

**Comment by tarek-ri** [comment] 2021-01-26 22:12
Any info on this one ?

**Comment by eyalbe4** [comment] 2021-01-27 08:42
Thanks for reporting this issue @tarek-ri.
We'll be looking into it soon.

**Comment by yahavi** [comment] 2021-01-27 17:28
@tarek-ri 
Thanks for reporting this issue. We are working on a fix. 

The root cause is as following:
When trying to collect the build info, the CLI searches for setup.py to extract the module name. If there isn't a setup.py file in the current directory, the execution fails. 

To resolve this issue, if there isn't a setup.py file in the current working directory, set the module name to be the build name. You can read more about this issue and the possible resolution at https://github.com/jfrog/jfrog-cli-core/pull/62.

As a workaround for now, you can add the `--module` flag with a module name:
```sh
jfrog rt pipi --upgrade pip setuptools wheel poetry --module my-module 
```
The module name will appear in the build-info in Artifactory after running `jfrog rt build-publish`.

We'd appreciate your feedback on that.

**Comment by eyalbe4** [comment] 2021-03-21 13:46
@tarek-ri,
I'm closing this issue for now, but please let us know if you need additional assistance or have any feedback following @yahavi's reply.

**Closed by eyalbe4** 2021-03-21 13:46 UTC
Labels: question
