### ISSUE TITLE
jfrog release 2.46.0 invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fliiiix** [jfrog/jfrog-cli#2155] opened 2023-08-24 08:55 UTC
### Describe the bug

```
$ jfrog -v
jf version 2.46.0
$ jfrog config add --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_APIKEY --interactive=false
```

adding a configuration fails

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0xc8a496]
goroutine 1 [running]:
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).resolveServerId(...)
	/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:318
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).prepareConfigurationData(0xc0006d0568)
	/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:287 +0x156
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).config(0xc0006d0568)
	/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:162 +0x25
github.com/jfrog/jfrog-cli-core/v2/common/commands.(*ConfigCommand).Run(0xc0006d0568)
	/go/pkg/mod/github.com/jfrog/jfrog-cli-core/v2@v2.41.0/common/commands/config.go:132 +0x271
github.com/jfrog/jfrog-cli/config.addOrEdit(0xc0002c6160, 0x0)
	/jfrog-cli/config/cli.go:139 +0x1[46](https://code.roche.com/simulacrum/simulacrum/-/jobs/29497217#L46)
github.com/jfrog/jfrog-cli/config.addCmd(0xc0002c6160)
	/jfrog-cli/config/cli.go:94 +0x65
github.com/urfave/cli.HandleAction({0xf039a0?, 0x114c590?}, 0x3?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x[50](https://code.roche.com/simulacrum/simulacrum/-/jobs/29497217#L50)
github.com/urfave/cli.Command.Run({{0x1070340, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x10bfc97, 0x1c}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175 +0x67b
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00028a000, 0xc0002c62c0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:405 +0xe87
github.com/urfave/cli.Command.startApp({{0x1077c9c, 0x6}, {0x0, 0x0}, {0xc0003cc0d0, 0x1, 0x1}, {0x109809f, 0x10}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:380 +0xb7f
github.com/urfave/cli.Command.Run({{0x1077c9c, 0x6}, {0x0, 0x0}, {0xc0003cc0d0, 0x1, 0x1}, {0x109809f, 0x10}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:103 +0x845
github.com/urfave/cli.(*App).Run(0xc00028a700, {0xc0000340a0, 0xa, 0xa})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0xb87
main.execMain()
	/jfrog-cli/main.go:129 +0x3[53](https://code.roche.com/simulacrum/simulacrum/-/jobs/29497217#L53)
main.main()
	/jfrog-cli/main.go:[74](https://code.roche.com/simulacrum/simulacrum/-/jobs/29497217#L74) +0x25
```

### Current behavior

see Describe the bug

### Reproduction steps

I use the official docker image

```
releases-docker.jfrog.io/jfrog/jfrog-cli-v2 with digest releases-docker.jfrog.io/jfrog/jfrog-cli-v2@sha256:90a89c36668ad7dd7e2a29b01107e87f17e5d26ef20b98ebf398fe13aabb3124
```

And then just run 

```
$ jfrog config add --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_APIKEY --interactive=false
```

(in a gitlab ci job)

### Expected behavior

not to crash ideally 

### JFrog CLI version

2.46.0

### Operating system type and version

 releases-docker.jfrog.io/jfrog/jfrog-cli-v2@sha256:90a89c36668ad7dd7e2a29b01107e87f17e5d26ef20b98ebf398fe13aabb3124

**Comment by RobiNino** [comment] 2023-08-24 11:05
Hi @fliiiix ,
Sorry for the inconvenience caused by this, please see my reply in this [similar issue](https://github.com/jfrog/jfrog-cli/issues/2153#issuecomment-1691375253).
Closing due to duplication with #2153.

**Closed by RobiNino** 2023-08-24 11:05 UTC
Labels: bug
