### ISSUE TITLE
Artifactory Maven Task Azure Devops TFS Started Failing after Version 1.26.1

### ISSUE THREAD

**Issue by psgmurugan** [jfrog/jfrog-cli#492] opened 2019-11-08 15:58 UTC
Artifactory Maven Task Fails to identify the maven build info extractor even if placed under the proper JFROGCLIDEPENDENCYDIR.  A change broke the Azure Devops TFS Task. 

The file build-info-extractor-maven3-2.13.10-uber.jar is already available under $(Agent.WorkFolder)\_jfrog\.jfrog\dependencies\maven

And the task still tries to download from Internet. Suspecting Release 1.27.0 broke this

**Comment by psgmurugan** [comment] 2019-11-08 16:39
I think the code was changed to organize the build info extractor into a folder. However the document does not reflect the same. 

https://www.jfrog.com/confluence/display/RTF/Azure+DevOps+and+TFS+Artifactory+Extension

I was able to resolve the issue by 
placing the jar file under $(Agent.WorkFolder)\_jfrog\.jfrog\dependencies\maven\<mavenExtractorDependencyVersion> instead of $(Agent.WorkFolder)\_jfrog\.jfrog\dependencies\maven. However this change is not documented on the Artifactory Maven Task doc.

**Comment by eyalbe4** [comment] 2019-11-08 17:14
@psgmurugan,
Thank you so much for reporting this issue and also figuring out the root cause.
We will fix the documentation shortly. Apologies for the in convenience caused by this error.

**Comment by eyalbe4** [comment] 2019-11-10 07:19
The documentation is now fixed @psgmurugan. Thanks again!
BTW, we recommend using the [Artifactory Tools Installer](https://www.jfrog.com/confluence/display/RTF/Azure+DevOps+and+TFS+Artifactory+Extension#AzureDevOpsandTFSArtifactoryExtension-ArtifactoryToolsInstaller) to get both JFrog CLI and the Maven Extractor installed on the build agent.

**Comment by psgmurugan** [comment] 2019-11-10 22:24
Thank you for your quick support on this.

**Closed** 2019-11-10 22:24 UTC
