### ISSUE TITLE
jfrog.exe missing from version 2.6.0

### ISSUE THREAD

**Issue by acohenOT** [jfrog/jfrog-cli#1300] opened 2021-11-21 22:36 UTC
**Describe the bug**
jfrog.exe missing after updating jfrog-cli-v2 to 2.6.0 using npm.

**To Reproduce**
On Windows, run `npm install -g jfrog-cli-v2`
Run `jfrog`
Error: jfrog is not recognized as an internal or external command, operable program or batch file.
jfrog.exe missing from C:\Program Files\nodejs\node_modules\jfrog-cli-v2\bin\

**Expected behavior**
jfrog.exe present in C:\Program Files\nodejs\node_modules\jfrog-cli-v2\bin\

**Versions**
- JFrog CLI version: 2.6.0
- JFrog CLI operating system: Windows

**Additional context**
Workaround, downgrade to npm 2.5.1
run `npm install -g jfrog-cli-v2@2.5.1`

**Comment by eyalbe4** [comment] 2021-11-21 22:44
Thank you for reporting this @acohenOT!
We're investigating this. We'll send out an update here.

**Comment by RobiNino** [comment] 2021-11-22 16:47
Hi @acohenOT ,
We just released 2.6.1 which fixes this issue.
We'd appreciate your feedback for it.
Sorry for the inconvenience caused by this.

**Comment by acohenOT** [comment] 2021-11-22 17:04
It works now using 2.6.1. Thank you.

**Comment by axel3rd** [comment] 2021-11-22 17:59
> We just released 2.6.1 which fixes this issue.

If 2.6.1 could be released in [GitHub releases](https://github.com/jfrog/jfrog-cli/releases) it would be nice 😁.

Tricky use case of an OS image build in error, "just now":
- Check last JFrog CLI version from [GitHub API](https://api.github.com/repos/jfrog/jfrog-cli-go/releases/latest): 2.6.0
- Get it from https://releases.jfrog.io/artifactory/jfrog-cli/v2/, doesn't exist

**Comment by RobiNino** [comment] 2021-11-22 18:16
@axel3rd ,
Fixed now as well.
Thanks!

**Closed** 2021-11-23 06:58 UTC
Labels: bug
