### ISSUE TITLE
CLI claims it couldn't find plexus-classworlds-x.x.x.jar with maven 3.6.3

### ISSUE THREAD

**Issue by TimDG** [jfrog/jfrog-cli#511] opened 2019-11-29 12:35 UTC
Hi,

I'm trying to get jfrog cli to run inside a docker image. However it always complains that the plexus classworlds jar is not found.

I've made sure that the M2_HOME env variable points to the right location and I can see that the jar is actually present in the boot folder in there:

```
root@0e0533fc62b3:/source# ./jfrog rt mvn "clean package" .jfrog/mvnconfig.yml 
[Info] Running Mvn...
[Info] Downloading bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-maven3/2.13.13/build-info-extractor-maven3-2.13.13-uber.jar
[Info] Downloaded 1 artifact.
[Error] couldn't find plexus-classworlds-x.x.x.jar in Maven installation path, please check M2_HOME environment variable
root@0e0533fc62b3:/source# ls -l $M2_HOME/boot/
total 72
drwxr-xr-x 2 root root  4096 Nov 28 17:26 .
drwxr-xr-x 1 root root  4096 Nov 28 17:26 ..
-rw-r--r-- 1 root root 52873 Nov  7 12:32 plexus-classworlds-2.6.0.jar
-rw-r--r-- 1 root root 11560 Nov  7 12:32 plexus-classworlds.license
root@0e0533fc62b3:/source# 
```

I've used this docker image: maven:3.6.3-jdk-8 
With maven:3.6.2-jdk-8 it works as intended

**Comment by TimDG** [comment] 2019-11-29 12:53
To be a bit more complete: I installed jfrog using the `curl -fL https://getcli.jfrog.io | sh` script

**Comment by ingokofler** [comment] 2019-12-02 13:33
Also affected by this one. Issue is related to latest DockerHub image and the way how they implemented the check...

https://github.com/jfrog/jfrog-cli/blob/master/artifactory/commands/mvn/mvn.go#L153-L163

```go
plexusClassworlds, err := filepath.Glob(filepath.Join(mavenHome, "boot", "plexus-classworlds*"))
```

will find both the .jar and the .license file. The .license file does not exist in previous Maven Docker image versions. So the plexusClassworlds will have two elements and the following check then fails

```go
if len(plexusClassworlds) != 1 {
		return nil, errorutils.CheckError(errors.New("couldn't find plexus-classworlds-x.x.x.jar in Maven installation path, please check M2_HOME environment variable"))
	}
```

As a workaround you can simply rename or remove the .license file. This works for us but the check should be fixed upstream ASAP.

**Comment by eyalbe4** [comment] 2019-12-02 13:56
@TimDG and @ingokofler - thanks for reporting and pinpointing the root cause!
Looks like replacing "plexus-classworlds*" with "plexus-classworlds*.jar" should resolve the issue.
I'll create a PR with the fix.

**Comment by TimDG** [comment] 2019-12-19 14:56
Looks like it's fixed. Thanks!

**Closed** 2019-12-19 14:55 UTC

**Comment by planetf1** [comment] 2020-01-17 10:58
We fell foul of this using the azure dev pipelines Artifactory task.
Fortunately the above tips and links helped - resolved. https://github.com/odpi/egeria/issues/2442 FYI
Hopefully jfrog will fix their plugin soon

**Comment by shapeofarchitect** [comment] 2021-04-21 09:56
Can anyone please tell me which Docker Image this fix went into ? I am facing the same issue with `maven:3.6.3-jdk-8`

**Comment by yahavi** [comment] 2021-04-21 12:08
@shapeofarchitect,
Please try to set the following environment variable with your docker image:
`M2_HOME=/usr/share/maven`

**Comment by shapeofarchitect** [comment] 2021-04-21 12:39
yes with the image 3.6.3 and setting M2_HOME=/usr/share/maven fixes the issue.

**Comment by leemeador** [comment] 2021-05-11 01:05
If you would take care of the jfrog cli not needing M2 home when running on GitHub workflows, this would not be a problem when they change the mvn version and path on their build agents. Please take care of that.

**Comment by eyalbe4** [comment] 2021-05-11 06:31
Definitely @leemeador.
This is something we are planning to implement.

**Comment by vb-chris** [comment] 2022-02-14 15:14
Although this issue is closed, I'm still facing it using one of the latest binaries

* `https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.12.1/jfrog-cli-windows-amd64/jf.exe` and
* `https://releases.jfrog.io/artifactory/jfrog-cli/v2/2.12.1/jfrog-cli-windows-amd64/jfrog.exe`

in combination with maven 3.6.3. Isn't the merge from 12/2019 included in these binaries?
