### ISSUE TITLE
 1.35.5 - INVALID CHECKSUMS produced by Jfrog CLI - Artifactory reports 409 because of it

### ISSUE THREAD

**Issue by alexmnyc** [jfrog/jfrog-cli#723] opened 2020-06-03 20:10 UTC
Using jfrog cli 1.35.5 to publish to Artifactory reports incorrect checksums and returns 409

Using Jfrog cli 1.32.4 to publish gradle builds to Artifactory, works as expected.

```
$ md5sum api-security-1.0.19-SNAPSHOT.jar
e342f9c0f633a8f3963aff4a52f29d2a api-security-1.0.19-SNAPSHOT.jar

$ sha1sum api-security-1.0.19-SNAPSHOT.jar
a599acbb955b933dfbdc2d1f684061fbad43a5e9 api-security-1.0.19-SNAPSHOT.jar

$ shasum -a256 api-security-1.0.19-SNAPSHOT.jar
c289f8d3618357897e3d8c500a74676734d85169d3647fae23f70291e40528b0 api-security-1.0.19-SNAPSHOT.jar

Artifactory 409 error reports this:

{
checksums = {
SHA - 1 = ChecksumInfo

{ type = SHA - 1, original = '26c15a328950d10f1cd75a5eeb9108c38b3147bd', actual = 'a599acbb955b933dfbdc2d1f684061fbad43a5e9' }
,
MD5 = ChecksumInfo

{ type = MD5, original = 'e629e280cb3b84fae1da87557ef0dec1', actual = 'e342f9c0f633a8f3963aff4a52f29d2a' }
,
SHA - 256 = ChecksumInfo

{ type = SHA - 256, original = 'null', actual = 'c289f8d3618357897e3d8c500a74676734d85169d3647fae23f70291e40528b0' }
}
}
```

Example response:

```
> Task :artifactoryDeploy FAILED
 FAILURE: Build failed with an exception.
 * What went wrong:
 Execution failed for task ':artifactoryDeploy'.
 > java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Failed to deploy file. Status code: 409 Response message: Artifactory returned the following errors: 
   Checksum policy 'LocalRepoChecksumPolicy: CLIENT' rejected the artifact 'libs-snapshot-local:com/ur-test/api-security/1.0.19-SNAPSHOT/api-security-1.0.19-SNAPSHOT.jar'. Checksums info: ChecksumsInfo{checksums={SHA-1=ChecksumInfo{type=SHA-1, original='26c15a328950d10f1cd75a5eeb9108c38b3147bd', actual='a599acbb955b933dfbdc2d1f684061fbad43a5e9'}, MD5=ChecksumInfo{type=MD5, original='e629e280cb3b84fae1da87557ef0dec1', actual='e342f9c0f633a8f3963aff4a52f29d2a'}, SHA-256=ChecksumInfo{type=SHA-256, original='null', actual='c289f8d3618357897e3d8c500a74676734d85169d3647fae23f70291e40528b0'}}} Status code: 409
```

**Comment by barbelity** [comment] 2020-06-04 12:46
@alexmnyc thanks for opening this issue.
Checksum mismatch can sometimes be caused by network issues, is this error consistent?

As I wasn't able to reproduce the issue on my machine:
1. Is this also happening in other gradle builds? Can you please try building [our gradle project example](https://github.com/jfrog/project-examples/tree/master/gradle-examples/gradle-example) and share the outcome?
2. Which version of Artifactory do you use?
3. What is the CLI command you run?

**Comment by alexmnyc** [comment] 2020-06-04 15:04
The error is consistent for the same codebase on different CI instances and publishing to two different artifactories

Artifactory version is 6.18.1 rev 61801900

**Comment by alexmnyc** [comment] 2020-06-04 15:10
Is original value what Jfrog clients calculates and sends it to artifactory? That value seems to be incorrect 

It works for some builds, especially with gradle 5 6 etc

This specific build is using gradle wrapper 4.10 
Shadow plugin 4.0.3

**Comment by eyalbe4** [comment] 2020-06-04 15:38
@alexmnyc,
Can you please help us reproduce this issue? Maybe share a simple gradle project in GutHub that shows this issue.
Thanks!

**Comment by alexmnyc** [comment] 2020-06-04 15:44
The code is proprietary as I work at TRP. Scott, on our team, opened a ticket with you guys internally I believe 134708

**Comment by rhowe** [comment] 2020-06-08 09:41
I work with @alexmnyc and can report that JFrog CLI 1.36.0 does not exhibit this behaviour, whereas 1.35.5 does.
There's nothing in the release notes which looks relevant and nothing in the commit history that jumps out at me either.

jfrog-client-go has been updated from 0.9.0 to 0.11.0 but there's nothing in the release notes for that which seems relevant

build-info-gradle-extractor has been updated from 4.15.0 to 4.15.2 - I wonder if this PR is the cause for the fixed behaviour: https://github.com/jfrog/build-info/pull/336


As an aside I see that the default environment variable excludes have been changed with 1.36.0 so that environment variables with "psw" in their name are no longer published with buildinfo, but this is not mentioned in the release notes. It doesn't affect us but seems worth pointing out.

**Comment by eyalbe4** [comment] 2020-06-08 10:25
Thanks for the update @rhowe!
We will update the release notes with the **psw** exclude addition. Sorry for missing that.

As for the actual checksum issue, this still remains a mystery. I can't think of anything right now that can cause this. Please let me know if you'd like us to continue working together to figure this one out. If not, feel free to close this issue for now.

**Comment by eyalbe4** [comment] 2020-06-15 09:01
Closing this issue for now @rhowe. Please let me know if you'd like to continue looking into this together.

**Closed by eyalbe4** 2020-06-15 09:01 UTC
Labels: bug
